# Practical Questions:

# 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns

In [15]:
import numpy as np
arry=np.random.randint(1,10, size=(3,3))
print(arry)
print(f"Interchnage of array is \n{arry.T}\n")

[[6 1 1]
 [6 7 8]
 [8 7 7]]
Interchnage of array is 
[[6 6 8]
 [1 7 7]
 [1 8 7]]



# 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [25]:
arry2=np.random.randint(1,10, size=(10))
print(f"Array is: {arry2}")
print(f"Array in 2*5 is:-\n{arry2.reshape(2,5)}\n")

Array is: [9 5 5 3 4 4 7 9 4 4]
Array in 2*5 is:-
[[9 5 5 3 4]
 [4 7 9 4 4]]



# 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [46]:
arry3=np.random.rand(4,4)
bordered_array = np.pad(arry3, pad_width=1, mode='constant', constant_values=0)
print(f"Array is:\n {bordered_array}")

Array is:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.81699754 0.59304334 0.93688977 0.01862155 0.        ]
 [0.         0.47219178 0.83743886 0.7299142  0.13950952 0.        ]
 [0.         0.54732347 0.57606167 0.4231466  0.41236345 0.        ]
 [0.         0.82883398 0.69848574 0.22314644 0.63868078 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


# 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5

In [58]:
arry4=np.arange(10,61,5, dtype=int)
print(f"Array is: {arry4}")

Array is: [10 15 20 25 30 35 40 45 50 55 60]


# 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations   (uppercase, lowercase, title case, etc.) to each element

In [71]:
arry5=np.array(['Python','numpy','pandas'])
print(f"Upper Case:-\t{np.char.upper(arry5)}")
print(f"Upper Case:-\t{np.char.lower(arry5)}")
print(f"Upper Case:-\t{np.char.title(arry5)}\n")

Upper Case:-	['PYTHON' 'NUMPY' 'PANDAS']
Upper Case:-	['python' 'numpy' 'pandas']
Upper Case:-	['Python' 'Numpy' 'Pandas']



# 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [78]:
arry6=np.array(['Python','numpy','pandas'])
print(f"After adding space beween each letter of word is:-\n{np.char.join(" ",arry6)}\n")

After adding space beween each letter of word is:-
['P y t h o n' 'n u m p y' 'p a n d a s']



# 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division

In [103]:
arryOne=np.random.randint(1,5,size=(2,3))
arryTwo=np.random.randint(6,10,size=(2,3))
print(f"Given arrays\n Array1\n{arryOne}\nArray2\n{arryTwo}")
print(f" Addition of 2D array is:\n{np.add(arryOne,arryTwo)}\n")
print(f" Subtraction of 2D array is:\n{arryOne-arryTwo}\n")
print(f" Multiplication of 2D array is:\n{arryOne*arryTwo}\n")
print(f" Devision of 2D array is:\n{arryOne/arryTwo}\n")

Given arrays
 Array1
[[4 4 2]
 [4 4 1]]
Array2
[[8 7 9]
 [7 9 6]]
 Addition of 2D array is:
[[12 11 11]
 [11 13  7]]

 Subtraction of 2D array is:
[[-4 -3 -7]
 [-3 -5 -5]]

 Multiplication of 2D array is:
[[32 28 18]
 [28 36  6]]

 Devision of 2D array is:
[[0.5        0.57142857 0.22222222]
 [0.57142857 0.44444444 0.16666667]]



#  8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements

In [113]:
arry8=np.eye(5)
print(f"Indentity Matrix is:\n{arry8}")
print(f"Diagonal Elements are:\n{np.diagonal(arry8)}\n")

Indentity Matrix is:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements are:
[1. 1. 1. 1. 1.]



# 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [118]:
import numpy as np
arry9 = np.random.randint(0, 1000, size=100)
print("Random Integers:\n", arry9)

def is_prime(n):
    """Check if a number is prime."""
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

prime_numbers = [num for num in arry9 if is_prime(num)]

# Display the prime numbers
print("Prime Numbers in the Array:\n", prime_numbers)


Random Integers:
 [623 919 555 168 774 266 697  78 279 561  88 210 654 778  93 536 244 815
 826 836 284 977 220 198 637 242 762 572 416 429 297 170 665 270 698 476
 453 570 161 619 865  36 795  65 985 449 969 898 574 134 263 522  76 982
 998 364 338 987 582 189 951 227 576 180 881 289 137 493 493 396  27 652
 622 113  63 139 700 370 153 749 154 728 177 212  28 676 977 784 680 297
  38 683 529 507 867 260 580 588 392 555]
Prime Numbers in the Array:
 [919, 977, 619, 449, 263, 227, 881, 137, 113, 139, 977, 683]


# 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly  averages.

In [121]:
import numpy as np

daily_temperatures = np.random.randint(15, 31, size=30)
print("Daily Temperatures for the Month:\n", daily_temperatures)
weekly_temperatures = daily_temperatures[:28].reshape(4, 7)
print("\nWeekly Temperatures:\n", weekly_temperatures)
weekly_averages = np.mean(weekly_temperatures, axis=1)
print("\nWeekly Averages:\n", weekly_averages)


Daily Temperatures for the Month:
 [15 24 25 21 29 20 17 24 28 16 15 18 18 28 17 23 24 25 25 16 21 15 30 15
 29 17 27 29 23 17]

Weekly Temperatures:
 [[15 24 25 21 29 20 17]
 [24 28 16 15 18 18 28]
 [17 23 24 25 25 16 21]
 [15 30 15 29 17 27 29]]

Weekly Averages:
 [21.57142857 21.         21.57142857 23.14285714]
